### ISSUE TITLE
Does not handle artifacts without fully qualified names gracefully

### ISSUE THREAD

**Issue by sajayantony** [oras-project/oras#118] opened 2019-08-30 02:00 UTC
To repro the issue use an image that is not fully qualified as seen below. 

```
 1 ❯ oras push test:test .
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/deislabs/oras/vendor/github.com/containerd/containerd/reference.Spec.Hostname(0xc000022bb0, 0x9, 0x0, 0x0, 0x147b544, 0xc0001db788)
...
```

**Comment by adewaleo** [comment] 2019-10-02 03:29
I don't know if this is related, pushing without a tag does not automatically create a latest tag:

```
[08:26 PM] Work-Mac:temp tosin$ oras push ovatestregistry.azurecr.io/test3-txt test.txt
Uploading 114811b0b899 test.txt
Pushed ovatestregistry.azurecr.io/test3-txt
Digest: sha256:e791036240e581d536825b890fb712b7ee3b1ebfb2bad375c0aa3b9fd1cf82f0
[08:26 PM] Work-Mac:temp tosin$ 
[08:26 PM] Work-Mac:temp tosin$ 
[08:26 PM] Work-Mac:temp tosin$ oras pull ovatestregistry.azurecr.io/test3-txt
Error: image reference format is invalid. Please specify <name:tag|name@digest>
[08:26 PM] Work-Mac:temp tosin$ oras pull ovatestregistry.azurecr.io/test3-txt:latest
Error: ovatestregistry.azurecr.io/test3-txt:latest: not found
[08:26 PM] Work-Mac:temp tosin$ 
[08:27 PM] Work-Mac:temp tosin$ 
```

But pushing with the tag works:
```
[08:27 PM] Work-Mac:temp tosin$ oras push ovatestregistry.azurecr.io/test3-txt:latest test.txt
Uploading 114811b0b899 test.txt
Pushed ovatestregistry.azurecr.io/test3-txt:latest
Digest: sha256:e791036240e581d536825b890fb712b7ee3b1ebfb2bad375c0aa3b9fd1cf82f0
[08:27 PM] Work-Mac:temp tosin$ 
[08:27 PM] Work-Mac:temp tosin$ 
[08:27 PM] Work-Mac:temp tosin$ oras pull ovatestregistry.azurecr.io/test3-txt:latest
Downloaded 114811b0b899 test.txt
Pulled ovatestregistry.azurecr.io/test3-txt:latest
Digest: sha256:e791036240e581d536825b890fb712b7ee3b1ebfb2bad375c0aa3b9fd1cf82f0
[08:27 PM] Work-Mac:temp tosin$ 
```

**Comment by shizhMSFT** [comment] 2019-11-11 05:30
@adewaleo This is not related. For not creating a latest tag, it is a feature of `containerd`, which is by design.

**Comment by shizhMSFT** [comment] 2019-11-11 05:55
@sajayantony The bug is caused by https://github.com/containerd/containerd/issues/3817. The fix is proposed at https://github.com/containerd/containerd/pull/3818.

**Comment by SteveLasker** [comment] 2020-09-13 22:56
This looks like an issue where other clients may assume no registry = docker hub. We've made an explicit decision to not support default registry behavior. 
It would be a great [good first issue](https://github.com/deislabs/oras/labels/good%20first%20issue) for anyone that would like to [help](https://github.com/deislabs/oras/labels/help%20wanted) with.

**Comment by shizhMSFT** [comment] 2022-05-07 12:37
Closing as it has been addressed.

**Closed by shizhMSFT** 2022-05-07 12:37 UTC
Labels: bug, help wanted, good first issue
