### ISSUE TITLE
oras login is failing for ghcr.io with the oras cli version 0.13

### ISSUE THREAD

**Issue by suyash691** [oras-project/oras#446] opened 2022-07-13 11:02 UTC
With the newer version of oras cli, oras login is failing for ghcr.io with `Error: invalid reference: invalid registry`, while the older version works.
<img width="1517" alt="Screenshot 2022-07-13 at 4 31 22 PM" src="https://user-images.githubusercontent.com/9547836/178718841-0b257aaf-7ede-4466-888d-af3116bb6637.png">

**Comment by suyash691** [comment] 2022-07-13 11:17
@qweeah can you take a look at this since i see that the login implementation was changed in this [PR](https://github.com/oras-project/oras/pull/367/files)

**Comment by satyaye** [comment] 2022-07-15 04:19
@shizhMSFT - Can you please look into this since you have reviewed the referred PR earlier? I could not reach @qweeah

**Comment by qweeah** [comment] 2022-07-15 04:29
@suyash691  @satyaye Looking into it.

**Comment by qweeah** [comment] 2022-07-15 04:36
@suyash691 You don't need to specify the https, `oras login ghcr.io -u *****` should do the job.

**Comment by qweeah** [comment] 2022-07-15 04:46
@shizhMSFT Do we need to support the protocol check for login? BTW the protocal prefix can be recognized by docker cli but not for crane.

**Comment by suyash691** [comment] 2022-07-15 10:21
IMO this would be a breaking change for end-users who have been using the protocol prefixes in the older version of the CLI, so it should be supported still or the CLI should inform with a message on login that this is no longer supported.
We have seen some end users CIs breaking due to this change without any information as such

**Comment by warrenb-cgi** [comment] 2022-07-15 14:39
It's at minimum a documentation defect: https://oras.land/implementors/#github-packages-container-registry-ghcr

**Comment by shizhMSFT** [comment] 2022-07-21 14:56
@suyash691 The usage of `oras login https://ghcr.io` with the prefix `https://` was a mistake in the first place. To fix this mistake, we removed this "feature" / bug.

Although `docker login` also allows the prefix `https://` and `http://`, it's also a mistake. Running
```sh
docker login http://ghcr.io
```
does not guarantee the docker cli will use HTTP. Instead, it will still use HTTPS.

Similarly, running
```sh
docker login https://localhost:5000
```
does not guarantee the docker cli will use HTTPS. Instead, it will still use HTTP.

I would like to consider this as a minor _security improvement._ /cc @FeynmanZhou @yizha1

**Comment by shizhMSFT** [comment] 2022-07-26 03:41
Closing as by design.

**Closed by shizhMSFT** 2022-07-26 03:41 UTC
