### ISSUE TITLE
pushing annotations via --annotations-file causes manifest's config.mediaType to become 'unknown'

### ISSUE THREAD

**Issue by rchincha** [oras-project/oras#570] opened 2022-09-15 18:00 UTC
Testing against the zot registry. After pushing annotations, the conifg.mediaType changes to "unknown".

```
$ skopeo copy --format=oci --dest-tls-verify=false docker://alpine:edge docker://localhost:8080/alpine:edge

...

  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "config": {
    "mediaType": "application/vnd.oci.image.config.v1+json",
  
  
$ oras push --annotation-file /tmp/annotations.json localhost:8080/alpine:edge

...

  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "config": {
    "mediaType": "application/vnd.unknown.config.v1+json",
```

The annotations file only has `$manifest` entry.

```
$ cat /tmp/annotations.json
{"$manifest": {...}}
```

https://github.com/oras-project/oras/blob/main/cmd/oras/push.go#L163

This behavior seems wrong?

**Comment by rchincha** [comment] 2022-09-15 21:33
Looks like I can work around this by also specifying --artifact-type

**Comment by qweeah** [comment] 2022-09-16 02:18
> Looks like I can work around this by also specifying --artifact-type

Yes you can do that if you want to use an default config file.

If you want to customize the content of config file, you can also use `--config` parameter.

**Comment by shizhMSFT** [comment] 2022-09-16 14:52
Closing as the default `application/vnd.unknown.config.v1+json` is by design. It can be overwritten by `--artifact-type`.

**Closed by shizhMSFT** 2022-09-16 14:52 UTC
Labels: question
