### ISSUE TITLE
Using ORAS from snap can't authenticate with gcloud credential helper

### ISSUE THREAD

**Issue by jteichroeb-oanda** [oras-project/oras#1079] opened 2023-08-24 15:39 UTC
### What happened in your environment?

I'm using oras like this:
`oras push us-central1-docker.pkg.dev/... file.tar.gz`

I have docker configured to use gcloud auth using this command:
`gcloud auth configure-docker us-central1-docker.pkg.dev`

which sets up the ~/.docker/config.json like so:
```
{
  "credHelpers": {
    "us-central1-docker.pkg.dev": "gcloud"
  }
}
```

If I use oras from snap, authentication fails, but if I use the downloaded oras binary it works fine

### What did you expect to happen?

Authentication doesn't depend on 

### How can we reproduce it?

Since this requires authenticating with google cloud platform, replicating my setup isn't the easiest. I can help someone setup a similar environment if necessary 

### What is the version of your ORAS CLI?

1.0.0, which is the latest version in snap

### What is your OS environment?

Ubuntu 20.04

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.

**Comment by qweeah** [comment] 2023-08-25 08:59
Can you attach the debug log of failed oras push? You can get that with --debug flag set.

**Comment by qweeah** [comment] 2023-08-28 01:17
Thank @jteichroeb-oanda The logs at least show snap build doesn't pick up the stored creds from credHelper.

**Comment by qweeah** [comment] 2023-08-28 01:21
@jteichroeb-oanda Just to confirm when you using downloaded oras binary and it succeeds, is it `1.0.0` or `v1.0.1`?

**Comment by jteichroeb-oanda** [comment] 2023-08-28 01:25
@qweeah both 1.0.0 and 1.0.1 work. I can't try 1.0.1 with snap since the lastest I see is 1.0.0.

**Comment by qweeah** [comment] 2023-08-28 01:33
Got it, taking a look. Thanks for the input. @jteichroeb-oanda

**Comment by FeynmanZhou** [comment] 2023-08-29 05:49
Upgrading the ORAS installer to v1.0.1 on Snap is still in WIP and tracked in #965 .

**Comment by qweeah** [comment] 2023-08-29 08:18
@jteichroeb-oanda snap apps uses separated config file. You should add cred helper to the docker config in snap's virtual environment `~/snap/oras/current/.docker/config.json` and it should work.

**Comment by jteichroeb-oanda** [comment] 2023-08-29 13:41
@qweeah that doesn't quite work either, it doesn't have a way to call the credential helper:
```
Error: failed to resolve latest: GET "https://us-central1-docker.pkg.dev/v2/[...]/manifests/latest": error getting credentials - err: docker-credential-gcloud resolves to executable in current directory (./docker-credential-gcloud), out: ``
```

**Comment by qweeah** [comment] 2023-08-30 01:05
Looks like the credential helper needss to be accessible within the snap sandbox. I tried `--classic` installation and get the same error

> Error: error storing credentials - err: docker-credential-pass resolves to executable in current directory (./docker-credential-pass), out: ...

@FeynmanZhou Maybe we should suggest user not to use snap release if they are using credstore or credhelpers, or even remove snap from the installation guide.

**Comment by FeynmanZhou** [comment] 2023-08-30 01:07
@qweeah If there is no workaround for the issue caused by the Snap sandbox environment, we can consider removing the Snap installation from the installation guide and dropping its maintenance for future releases. 

@SamirPS Do you have any suggestions on this issue?

**Comment by shizhMSFT** [comment] 2023-08-30 01:27
[Snap](https://ubuntu.com/core/services/guide/snaps-intro) or _Snappy_ is a package management system in Ubuntu with applications **containerized** and **sandboxed**.

Since a snap application runs in a sandbox environment, snap version of `oras` is not able to read the docker config and credential helpers directly and thus causing user experience problems.
 
> [!NOTE]
> The home folder of the snap version of oras is `~/snap/oras/current`.

**Comment by jteichroeb-oanda** [comment] 2023-08-30 01:32
One thing that confuses me, I have the gcloud command installed from snap as well, if it can access files outside of the sandbox environment, can't oras do the same thing?

**Comment by shizhMSFT** [comment] 2023-08-30 01:38
`oras` can access the files outside of the sandbox. For example, `oras push <ref> file1 file2` where `file1` and `file2` can be at any place. However, `oras` cannot find `docker-credential-gcloud` in `$PATH` as `$PATH` has been modified by `snap`.

BTW, the error message _docker-credential-gcloud resolves to executable in current directory (./docker-credential-gcloud)_ of `oras v1.0.0` might be confusing. It is fixed in `v1.0.1` as _exec: "docker-credential-gcloud": executable file not found in $PATH_.

**Comment by shizhMSFT** [comment] 2023-08-30 01:51
Currently, `oras` is configured as `strict` [confinement level](https://snapcraft.io/docs/snap-confinement).

https://github.com/oras-project/oras/blob/999ac385ed704b1cb0dfa97c7b88e2ce7d290c3c/snapcraft.yaml#L20

I'm not sure if setting confinement level to `classic` and install using `--classic` works or not. Noto to @qweeah, `--classic` flag does not work as it is not declared as `classic`.

Another thing we can try is the [snap interfaces](https://snapcraft.io/docs/interfaces), mounting `:home` to `oras:home`.

**Comment by shizhMSFT** [comment] 2023-08-30 01:54
Oh. The `:home` is already connected.
```console
$ snap connections oras
Interface  Plug          Slot      Notes
home       oras:home     :home     -
network    oras:network  :network  -
```

**Comment by SamirPS** [comment] 2023-09-01 21:40
can it's been link to this ? https://forum.snapcraft.io/t/kubectl-wrong-gcloud-path-when-doing-any-operations/18848

**Comment by SamirPS** [comment] 2023-09-03 18:53
Normally, with this interface, the snap will work: https://snapcraft.io/docs/personal-files-interface , I will update the snapcraft.yaml file and let's you test it.

**Comment by qweeah** [comment] 2023-09-04 02:50
@SamirPS I don't think using the personal file interface will be a good solution since user might use any config file via `--config` and specify any cred helper in the configuration. During build time, we cannot list out every possible path.

**Comment by qweeah** [comment] 2023-09-04 04:33
> I'm not sure if setting confinement level to classic and install using --classic works or not. Noto to @qweeah, --classic flag does not work as it is not declared as classic.

Tried building a snapcraft version locally with confinement level set to `classic` and it worked: both config file and binaries can be successfully invoked. I think this is the most ideal solution we currently have.

**Comment by SamirPS** [comment] 2023-09-04 06:58
thanks for the head up, i let you do the PR and publish it then :)

**Comment by qweeah** [comment] 2023-11-06 06:30
Putting it to future milestone to avoid being flagged as stale. BTW we tried to convert oras a classic snap app and it's pending snapcraft owner's approval, see https://forum.snapcraft.io/t/request-for-classic-confinement-oras-and-oras-test/36826

**Closed** 2024-05-14 13:23 UTC
Labels: bug, logging, GCP
